In [ ]:
#------------Tutorial 03-------------------
# Create a new notebook and code the following

In [ ]:
# 1. Create a numpy array of size 2 x 2
arr = np.array([[1, 2], [3, 4]])
print(arr)


[[1 2]
 [3 4]]


In [ ]:
# 2. Create a random numpy array of size 3 x 4
random_array = np.random.rand(3, 4)
print(random_array)

[[0.81490257 0.47927175 0.68924197 0.85700796]
 [0.81725395 0.73565418 0.8867398  0.71202734]
 [0.80246064 0.10642947 0.32117452 0.68711627]]


In [ ]:
# 3. Create a numpy array of ones and a numpy array of zeroes
ones = np.ones((2, 2))
print(ones)

zeros = np.zeros((2, 2))
print(zeros)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [ ]:
# 4. Create a random numpy array of size 6x3 and transpose it
arr = np.random.rand(6, 3)
print(arr)

transposed = arr.T
print(transposed)



[[0.27387323 0.08777375 0.81851061]
 [0.70326669 0.45801755 0.21067   ]
 [0.54858771 0.91527626 0.06106588]
 [0.24435445 0.78302281 0.0701648 ]
 [0.73263822 0.58825161 0.01965569]
 [0.24884814 0.27482052 0.54400181]]
[[0.27387323 0.70326669 0.54858771 0.24435445 0.73263822 0.24884814]
 [0.08777375 0.45801755 0.91527626 0.78302281 0.58825161 0.27482052]
 [0.81851061 0.21067    0.06106588 0.0701648  0.01965569 0.54400181]]


In [ ]:
# 5. Create two random numpy array of size n x p and p x m and then compute the dot product
n = 3
p = 4
m = 2

array1 = np.random.rand(n, p)
array2 = np.random.rand(p, m)

print("Array 1 ({}x{}):\n".format(n, p), array1)
print("\nArray 2 ({}x{}):\n".format(p, m), array2)

dot_product = np.dot(array1, array2)

print("\nDot Product ({}x{}):\n".format(n, m), dot_product)

Array 1 (3x4):
 [[0.08881286 0.2031386  0.82333584 0.23907746]
 [0.86043745 0.39309654 0.22114955 0.48406547]
 [0.92079318 0.74675555 0.26441216 0.88310372]]

Array 2 (4x2):
 [[0.15794604 0.08729964]
 [0.77005683 0.43322596]
 [0.18691143 0.16479017]
 [0.06642331 0.6960735 ]]

Dot Product (3x2):
 [[0.3402271  0.39785138]
 [0.51209797 0.61880393]
 [0.82856017 1.06217643]]


In [ ]:
!git config --global user.email "ahmabdurrahman3@gmail.com"
!git config --global user.name "Versa03"

In [ ]:
!git clone https://github.com/Versa03/data-science-toolkit.git

Cloning into 'data-science-toolkit'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), done.


In [ ]:
%cd data-science-toolkit

/content/data-science-toolkit


In [2]:
!mv /content/TutorialW3.ipynb /content/data-science-toolkit

mv: cannot stat '/content/TutorialW3.ipynb': No such file or directory
